name: Build Nes-Emulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get install -y build-essential cmake zip

      - name: Install dependencies
        run: sudo apt-get install -y libsdl2-dev

      - name: Configure CMake (${{ matrix.config }})
        run: |
          mkdir -p build-${{ matrix.config }}
          cd build-${{ matrix.config }}
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DSDL2_DIR=/usr/lib/cmake/SDL2

      - name: Build
        run: |
          cd build-${{ matrix.config }}
          make

      - name: Package
        run: |
          cd build-${{ matrix.config }}
          mkdir package
          cp NesEmu package/
          cp ../README.md package/
          cd package
          zip -r ../../linux-${{ matrix.config }}.zip .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.config }}
          path: linux-${{ matrix.config }}.zip

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --quiet --norestart"

      - name: Install SDL2
        run: |
          Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-2.26.5/SDL2-2.26.5-win64-x64.zip" -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath C:\SDL2
          Remove-Item -Force SDL2.zip

      - name: Configure CMake (${{ matrix.config }})
        run: |
          mkdir -p build-${{ matrix.config }}
          cd build-${{ matrix.config }}
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.config }} -G "Visual Studio 16 2019" -DSDL2_DIR=C:/SDL2

      - name: Build
        run: |
          cd build-${{ matrix.config }}
          cmake --build . --config ${{ matrix.config }}

      - name: Package
        run: |
          cd build-${{ matrix.config }}
          mkdir package
          cp NesEmu.exe package/  # Ensure your Windows binary is NesEmu.exe
          cp ../README.md package/
          cp C:/SDL2/x64/SDL2.dll package/  # Copy the SDL2.dll from the SDL2 download
          cd package
          zip -r ../../windows-${{ matrix.config }}.zip .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.config }}
          path: windows-${{ matrix.config }}.zip
