name: Build Nes-Emulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get install -y build-essential cmake zip

      - name: Install dependencies
        run: sudo apt-get install -y libsdl2-dev

      - name: Configure CMake (${{ matrix.config }})
        run: |
          mkdir -p build-${{ matrix.config }}
          cd build-${{ matrix.config }}
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DSDL2_DIR=/usr/lib/cmake/SDL2

      - name: Build
        run: |
          cd build-${{ matrix.config }}
          make

      - name: Package
        run: |
          cd build-${{ matrix.config }}
          mkdir package
          cp NesEmu package/
          cp ../README.md package/
          cd package
          zip -r ../../linux-${{ matrix.config }}.zip .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.config }}
          path: linux-${{ matrix.config }}.zip

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-3.2.10/SDL3-devel-3.2.10-VC.zip" -OutFile "SDL3.zip"
          Expand-Archive -Path SDL3.zip -DestinationPath C:\SDL3
          Remove-Item -Force SDL3.zip

      - name: Configure CMake (${{ matrix.config }})
        run: |
            mkdir -p build-${{ matrix.config }}
            cd build-${{ matrix.config }}
            cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.config }} -G "Visual Studio 17 2022" -DSDL3_DIR=C:/SDL3/SDL3-3.2.10/cmake

      - name: Build
        run: |
          cd build-${{ matrix.config }}
          cmake --build . --config ${{ matrix.config }}

      - name: Package
        run: |
          cd build-${{ matrix.config }}
          mkdir package
          cp ${{ matrix.config }}/NesEmu.exe package/
          cp ../README.md package/
          cp C:/SDL3/SDL3-3.2.10/lib/x64/SDL3.dll package/
          cd package
          Compress-Archive -Path * -DestinationPath ../../windows-${{ matrix.config }}.zip

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.config }}
          path: windows-${{ matrix.config }}.zip
