name: Build Nes-Emulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get install -y build-essential cmake zip

      - name: Install dependencies
        run: sudo apt-get install -y libsdl2-dev

      - name: Configure CMake (${{ matrix.config }})
        run: |
          mkdir -p build-${{ matrix.config }}
          cd build-${{ matrix.config }}
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DSDL2_DIR=/usr/lib/cmake/SDL2

      - name: Build
        run: |
          cd build-${{ matrix.config }}
          make

      - name: Package
        run: |
          cd build-${{ matrix.config }}
          mkdir package
          cp NesEmu package/
          cp ../README.md package/
          cd package
          zip -r ../../linux-${{ matrix.config }}.zip .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.config }}
          path: linux-${{ matrix.config }}.zip
